root: true

ignorePatterns:
  - "!.*"
  - /coverage
  - /dist
  - /node_modules
  - /test/fixtures/types.ts

extends:
  - plugin:@mysticatea/es2020

globals:
  console: "off"

rules:
  no-console: error
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
        markers:
          - eslint
          - eslint-env
          - eslint-disable
          - eslint-enable
          - exported
          - globals
          - istanbul
      line:
        exceptions: ["-", "=", "/"]
        markers:
          - eslint-disable-line
          - eslint-disable-next-line
          - istanbul
          - "TODO:"
          - "FIXME:"
          - "/"
  "@mysticatea/ts/explicit-member-accessibility": "off"
  "@mysticatea/prettier": "off"

settings:
  node:
    tryExtensions:
      - .tsx
      - .ts
      - .mjs
      - .cjs
      - .js
      - .json
      - .node

overrides:
  - files: scripts/**
    rules:
      no-console: "off"

  - files: src/**
    rules:
      no-restricted-syntax: [error, ForOfStatement]
      "@mysticatea/prefer-for-of": "off"

  - files: test/fixtures/entrypoint.ts
    rules:
      "@mysticatea/ts/no-require-imports": "off"
      "@mysticatea/ts/no-var-requires": "off"
