root: true

ignorePatterns:
- /dist

extends:
  - plugin:@mysticatea/es2015
  - plugin:@mysticatea/+node

rules:
  new-cap: "off"
  valid-jsdoc: "off"
  import/newline-after-import: "off"
  import/first: "off"

overrides:
  - files: src/*
    globals:
      window: readonly
    rules:
      # To reduce size for babel-translation.
      no-restricted-syntax:
        - error
        - ClassDeclaration
        - ClassExpression
        - ForOfStatement
        - BinaryExpression[left.operator='typeof'][right.value='object']
      prefer-rest-params: "off"
      prefer-spread: "off"
      "@mysticatea/prefer-for-of": "off"

  - files: scripts/rollup.config.js
    extends: plugin:@mysticatea/+modules

  - files: test/types.mjs
    globals:
      __dirname: "readonly"
