name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 12.x, 10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm ci
      - name: Test
        run: npm run -s test:mocha
      - name: Send Coverage
        run: npm run -s codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
