name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm ci
      - name: Test
        run: npx run-s "test:{tsc,lint,format}"

  test-on-node:
    name: Test on Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 12.x, 10.x, "10.13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm ci
      - name: Test
        run: npm run test:mocha -- --only-node
      - name: Send Coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-on-browser:
    name: Test on Browsers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: |
          sudo apt-get install libbrotli1 libegl1 libopus0 libwoff1 \
            libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 \
            libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libopenjp2-7 \
            libwebpdemux2 libhyphen0 libgles2 gstreamer1.0-libav
          npm ci
      - name: Test
        run: npm run test:mocha -- --only-browsers
      - name: Send Coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
